
version: '3.8'

services:
  server:
    build: ../Bank-Management-Server
    ports:
      - "4000:4000"
    networks:
      - widgets

  mainfram:
    # hostname: localhost
    build: ../Bank-Management-Mainfram
    ports:
      - "3000:80"
    networks:
      - widgets

  nginexs:
    build: ./nginx
    restart: always
    ports:
      - "8080:80"
    links:
      - mainfram
      - server
    networks:
      - widgets
networks:
  widgets:
    driver: bridge
    ipam:
     config:
       - subnet: 172.11.0.0/16
         gateway: 172.11.6.254
         aux_addresses:
          pos: 172.11.1.2
          couchdb: 172.11.1.3
